language: node_js
sudo: false
node_js: 7
install:
    - npm install -g cordova semver
    - npm install
    - npm run prepare
script:
    - cd ..
    - cordova create cordova-plugin-twilio-common-test-project com.example.hello HelloWorld
    - cd cordova-plugin-twilio-common-test-project
    - cordova platform add browser
    - cordova plugin add ../cordova-plugin-twilio-common/
    - cordova build
    - cd ..
    - rm -rf cordova-plugin-twilio-common-test-project
    - cd cordova-plugin-twilio-common
    - export SEMVER_VERSION=$(semver ${TRAVIS_TAG})
    - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
deploy:
    provider: npm
    skip_cleanup: true
    email: ${AUTHOR_EMAIL_ADDR}
    api_key: ${AUTHOR_NPM_API_KEY}
    tag: latest
    on:
        tags: true
        condition: $TRAVIS_TAG = $SEMVER_VERSION && $TRAVIS_TAG = $PACKAGE_VERSION
