language: node_js
sudo: false
node_js: 4
install:
    - npm install -g cordova
script:
    - cd ..
    - cordova create cordova-plugin-twilio-common-test-project com.example.hello HelloWorld
    - cd cordova-plugin-twilio-common-test-project
    - cordova platform add browser
    - cordova plugin add ../cordova-plugin-twilio-common/
    - cordova build
    - cd ..
    - rm -rf cordova-plugin-twilio-common-test-project
    - cd cordova-plugin-twilio-common